//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int id_photo { get; set; }
        public int id_user { get; set; }
        public string path { get; set; }
        public byte[] binPath { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
