//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public int Floor_ID { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual Role Role { get; set; }
    }
}
